### ISSUE TITLE
Remove component list from brainvisa-cmake

### ISSUE THREAD

**Issue by denisri** [brainvisa/brainvisa-cmake#1]
---

Author Name: **Cointepas, Yann** (@sapetnioc)
Original Redmine Issue: 5669, https://bioproj.extra.cea.fr/redmine/issues/5669
Original Date: 2012-08-01
Original Assignee: Cointepas, Yann

---

Each time BrainVISA components list is changed, it is necessary to modify brainvisa-cmake (with bv_update_project_list) in order to update the CMake and Python files containing the componant list. This list should be moved somewhere else to make the change in brainvisa-cmake refelct only the changes in the code. This will simplify the configuration of brainvisa-cmake with bv_maker and will make it possible to see the new package even if  brainvisa-cmake has not been updated.

**Comment by ylep** [comment]
Is this still relevant @sapetnioc, or should we just close the issue?
