### ISSUE TITLE
The sitecustomize directory created by bv_maker conflicts with casa-distro “custom projects”

### ISSUE THREAD

**Issue by denisri** [brainvisa/brainvisa-cmake#14]
---

Author Name: **Leprince, Yann** (@ylep)
Original Redmine Issue: 18743, https://bioproj.extra.cea.fr/redmine/issues/18743
Original Date: 2018-08-21

---

None

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Leprince, Yann** (@ylep)
Original Date: 2018-08-21T09:53:53Z

---

When compiling a custom project in casa-distro, a @sitecustomize@ package is created by bv_maker in the @/casa/custom/build/python@, which hides the @sitecustomize@ package contained in @/casa/build/python@. The latter is executed explicitly with @exec@, but it fails to import @sitecustomize.bv_maker_pure_python@ because Python will search for it in @/casa/custom/build/python@.

*Suggested fix*: replace the sitecustomize package by a @sitecustomize.py@ module (the Python docs suggest that @sitecustomize@ should be a module, not a package), put the @bv_maker_pure_python.pth@ file directly in @/casa/build/python@, and simply use @site.addsitedir@ to process the @.pth@ file (see https://docs.python.org/2.6/library/site.html#site.addsitedir).

**Comment by sapetnioc** [comment]
What is the current status of this old issue ?

**Comment by ylep** [comment]
Well, we don't have “custom projects” nor `/casa/custom` anymore, so this issue is completely obsolete. Closing.
