### ISSUE TITLE
git lfs command is obsolete

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa-cmake#54]
When doind a new compilation with casa_distro, I saw the following :
```
$ git lfs clone --branch master https://github.com/brainvisa/brainvisa-share.git /casa/host/src/brainvisa-share/master
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'

'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
```

**Comment by ylep** [comment]
This warning is harmless, but we could simply use `git clone` if our casa-dev images have a recent enough `git` that allows the same performance as `git lfs clone`

**Comment by denisri** [comment]
Is the git in ubuntu 18.04 recent enough ? Is there a minimal version number to check ?
