### ISSUE TITLE
Syntax error in Python file make installation fail

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa-cmake#55]
When there is a syntax error in a Python file, the corresponding `.pyc` is not generated but its installation rule still exists in `Makefile`. Therefore, execution of `make install-runtime` fails.

**Comment by denisri** [comment]
Should we allow installing such projects since this reflexts an upstream error (which was actually not detected as an error...) ?

**Comment by sapetnioc** [comment]
We may also make the build fail for such errors. A failure at install time is too late.

**Comment by denisri** [comment]
I agree. Do we have the control over that ?
