### ISSUE TITLE
split brainvisa-share packaging into 2 (at least) components

### ISSUE THREAD

**Issue by denisri** [brainvisa/brainvisa-cmake#6]
---

Author Name: **Riviere, Denis** (@denisri)
Original Redmine Issue: 14091, https://bioproj.extra.cea.fr/redmine/issues/14091
Original Date: 2015-12-17

---

to avoid installing with anatomist (for instance) all heavy-weight data in brainvisa-share.
We could provide a lightweight package containing nomenclatures, syntax and other small files, and a second one containing models, templates etc.

**Comment by sapetnioc** [comment]
I doubt anyone will ever work on this issue. If you think I am wrong, fell free to reopen it.
