### ISSUE TITLE
bv_maker should not be installed by make install-runtime

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-cmake#69]
`bv_maker` (and other tools of brainvisa-cmake) are currently installed by `make install-runtime`, but they are not necessary

**Comment by denisri** [comment]
Actually I think they are necessary since they contain the `bv_env*` programs set, which are used to set the paths (maybe in `environment.sh` or a similar place)

**Comment by ylep** [comment]
Well `bv_env` and friends *are* definitely necessary, but `bv_maker` and other commands that are used only for compilation are not. I have implemented a change that does this and will push as soon as this is tested...
