### ISSUE TITLE
Create 5.0 branches

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-cmake#71]
- [x] create 5.0 branches
- [x] create 5.0 version in components_definition.py
- [x] set up nightly builds on 5.0 branch
- [x] check tomorrow if nightly builds run correctly

**Comment by ylep** [comment]
Issues to be solved in the process of creating the 5.0 branches:

- [ ] preclinical-imaging-iam: `project_info.cmake` says it is version 1.2.0

**Comment by ylep** [comment]
For the record, I apply branch protection rules to the 5.0 branch for GitHub-hosted projects:

- Branch name pattern: `[0-9].[0-9]`
- Restrict who can push to matching branches: brainvisa/release
- Allow deletions

**Comment by sapetnioc** [comment]
I thought we decided to name those branches `brainvisa-5.0` to allow to create them on project with different version (soma-workflow, populse_db, etc.). Preclinical-imaging-iam is not maintained anymore. I think we can skip it and remove it from bv_maker.

**Comment by ylep** [comment]
Special cases:

- [casa-distro](https://github.com/brainvisa/casa-distro) will continue to follow the `master` branch (should we create a `brainvisa-5.0` branch?)

**Comment by ylep** [comment]
> I thought we decided to name those branches `brainvisa-5.0`

For the projects that do not follow the BrainVISA versioning, yes, definitely. For all “internal” projects I understood that we would simply name the branches `5.0` (after all, @denisri has already set version to 5.0.0 in components_definition.py so 5.0 is really the version of the component).

Agreed, this means that the branch name changes for different projects... but we have components_definition.py to take care of this.

**Comment by ylep** [comment]
Looks like I created 5.0 branches for some projects that will not be part of the release:

- sulci-data
- tms
- possibly soma-io-gpl

**Comment by denisri** [comment]
Indeed they are not part of the release. Never mind...

**Comment by denisri** [comment]
>  capsul and soma-base: waiting for maintainer access to create the branch protection rule

I have set admin permissions to the `populse_admin` group.

**Comment by denisri** [comment]
Now that casa-distro setup_dev procedure runs inside a container (whether via `casa_distro setup_dev` or by running a `casa-dev` container), we need to build a new container whenever the supported distros/branches change.
I have built and uploaded a new `casa-dev-ubuntu-18.04.sif` container which supports `branch=5.0` and the new distros.

**Comment by ylep** [comment]
> I have built and uploaded a new `casa-dev-ubuntu-18.04.sif` container which supports `branch=5.0` and the new distros.

Thanks @denisri! Unfortunately I did not see your comment until now, in the meantime I have been working on changing `setup_dev` to bootstrap brainvisa-cmake when the environment is created, this should spare us some image rebuilds. PR coming soon...

**Comment by denisri** [comment]
In a general way, `setup_dev` needs updating both `brainvisa-cmake` and `casa-distro`: `brainvisa-cmake` needs its updated `components_definition.py` to get the new branch name and definition, while `casa-distro` possibly needs updated distros and at least the latest modifs which "unlocks" specifying branch name not being "`master`", "`integration`" or "`latest_release`".
Anyway using the image I have built yesterday we should be able to test things.

**Comment by denisri** [comment]
Builds and tests have correctly run for brainvisa-5.0 and cea-5.0 last night.
