### ISSUE TITLE
soma-io-gpl

### ISSUE THREAD

**Issue by ylep** [brainvisa/brainvisa-cmake#73]
Should we include `soma-io-gpl` in the `cea`, `brainvisa`, `bvdev` releases?

Now we have something that is not really consistent:

```python
'soma-io-gpl', {
                'groups': ['all', 'opensource', 'standard', 'cati_platform'],
```

**Comment by denisri** [comment]
It contains a single command, `dicom_viewer` which was a GUI to display DICOM files tags I think. It was developed by the Cati team, and I'm not sure it is really maintained: currently it prints a pydicom version error and doesn't seem to work in casa-distro. Anyway it should not be part of public brainvisa releases. Maybe "cea" ones, I'm not sure either.

**Comment by denisri** [comment]
I would be OK to remove it from `standard` and `opensource`.
