### ISSUE TITLE
Set default DESIRED_QT_VERSION to 5

### ISSUE THREAD

**Issue by nsouedet** [brainvisa/brainvisa-cmake#80]
Default DESIRED_QT_VERSION in brainvisa-cmake is always 4 (https://github.com/brainvisa/brainvisa-cmake/blob/master/cmake/brainvisa-compilation.cmake#L19). 
I think we should change it to 5 now. Moreover, I am not sure that all codes are QT4 compliant anymore.

**Comment by denisri** [comment]
Oh yes, sure !
