### ISSUE TITLE
Fusion brainvisa-cmake in casa-distro

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa-cmake#89]
Related to #88, if we ever do a major reduction of bv_maker, what about putting all code in casa-distro project and drop brainvisa-cmake ? They are more closely related than before. For instance, in #88 modifications, brainvsa-cmake needs `bv` command (located in casa-distro). And casa-distro has also code dedicated to `bv_maker`. My changes would need two specific branches in the two projects to modify the two commands. But I could put everything in casa-distro that may become the only mandatory project in sources of all distros.

**Comment by ylep** [comment]
For the sake of separation of concerns, I don't really like the idea of merging brainvisa-cmake into casa-distro. This would blur the distinction between the build system and the distribution infrastructure, we'd be tempted to entangle the codes more than necessary, and we'd risk completely closing the door to non-containerized builds.

**Comment by sapetnioc** [comment]
The ratio benefit/work is too low to keep this issue opened.
