### ISSUE TITLE
Syntax error in Python makes user image creation fail

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/brainvisa-cmake#91]
When a Python file has a syntax error, the corresponding `*.pyc` file is not generated and the install step fails during user image creation. This may be a good behavior for release images but non final user images are used to launch tests. No test at all can be started (in user environment).

**Comment by denisri** [comment]
Now .pyc files generation is not fatal any longer, thus a project with syntax errors in python files will not prevent all other projects to build or be tested. However this .pyc generation will not be tested, at the end, so it's not always what we want also. But we cannot have both...
