### ISSUE TITLE
`bv_system_info` and `python` vs. `python3`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [brainvisa/brainvisa-cmake#94]
**Is your feature request related to a problem? Please describe.**

On Ubuntu 22.04, only `python3` is available **by default**, not `python`.

**Describe the solution you'd like**

Change `#!/usr/bin/env python` to `#!/usr/bin/env python3`?

https://github.com/brainvisa/brainvisa-cmake/blob/f1f159493888e7b1e7fd7933fc73f4406a2a9bdf/bin/bv_system_info#L1

**Describe alternatives you've considered**

* Install [`python-is-python3`](https://packages.ubuntu.com/search?keywords=python-is-python3) on recent Ubuntu machines.
* Run the script using something like `python3 bin/bv_system_info || python bin/bv_system_info`.
* Delete the script from `brainvisa-cmake`, possibly from the Neurospin internal path `/i2bm/local/bin` too.

**Additional context**

I am not sure `python3` is available on CentOS, Fedora, etc.

**Comment by sapetnioc** [comment]
I believe this script is not used anymore in BrainVISA.

**Comment by sapetnioc** [comment]
I propose that you include the modification for Python 3 in your PR #93.

**Comment by denisri** [comment]
OK for me.

**Comment by DimitriPapadopoulos** [comment]
But does it have to work on Centos or Fedora, which may not have a `python3` executable, only `python`?

**Comment by DimitriPapadopoulos** [comment]
Besides, perhaps we just need to get rid of this script.
